Feature/migrate alarm switch to alarm control panel
basilfx/homeassistant-biketrax pull request #12
Opened 2022-08-09 08:06 UTC by vlebourl

This replaces the `Alarm` switch that controls arming the alarm with an alarm control panel entity.

![image](https://user-images.githubusercontent.com/5701372/183592934-1faa0273-472f-4ec1-9ef7-d99a79a970ea.png)
![image](https://user-images.githubusercontent.com/5701372/183592977-ac1bed7e-061a-464c-900f-a620d3fbc3fe.png)
![image](https://user-images.githubusercontent.com/5701372/183597375-06c5cda8-c529-4fe6-a9ca-db932adb27d8.png)
![image](https://user-images.githubusercontent.com/5701372/183597427-24e5b9a3-904d-4cd7-b20e-90dc314ca9f2.png)
![image](https://user-images.githubusercontent.com/5701372/183593013-51587f76-0962-4be5-ac7a-39e527f65c6b.png)

Small caveat, the UI always shows both Arm Home and Arm Away even if only one of them is added as a supported feature. To circumvent this, I added the local bool `_is_home` to present the state `Armed Home` if it's the one that has been selected by the user. This bool is set to false when disarmed, so the next time the alarm is armed from auto guarding for instance, `Armed Away` will be shown. 

From Home Assistant, it's quite easy to set an automation that arms with `Arm Home` if the device is detected at home, so I don't think that this caveat is such a problem.

2022-08-09 08:32 UTC, vlebourl commented
Trigger is synced with the stolen state:

triggered:
![image](https://user-images.githubusercontent.com/5701372/183602770-6cc4a4d0-a6ab-45ce-9157-b683c0003c84.png)

not triggered:
![image](https://user-images.githubusercontent.com/5701372/183602788-129e84a9-4ed7-40eb-b6f3-2fedeef8ff02.png)

this also allows to us the `alarm_control_panel.trigger` service to both trigger the alarm and turn on the `stolen` switch.

2022-09-29 07:18 UTC, vlebourl commented
Hey, now that version 0.2 has been out for a while, any chance you might reconsider this? I have it installed on my own prod instance through my fork, and it's working like a charm!

2022-09-29 07:33 UTC, basilfx commented
Yes, I will definitely consider this for a 0.3.0 version, but I'm currently busy with holidays and some other projects.

2022-09-29 07:35 UTC, vlebourl commented
No rush! Enjoye your holidays!

2022-10-17 19:48 UTC, basilfx requested changes

2022-10-17 19:48 UTC, basilfx commented on .github/pr-labeler.yml
> +feature: ['feature/*', 'feat/*']
I'm not planning in using the pr-labeler (yet). Can you remove it from this PR?

2022-10-17 19:48 UTC, basilfx commented on .github/workflows/pr-labeler.yml
> +name: PR Labeler
I'm not planning in using the pr-labeler (yet). Can you remove it from this PR?

2022-10-17 19:48 UTC, basilfx commented on custom_components/biketrax/alarm_control_panel.py
> +"""Support for Overkiz Alarms."""
```suggestion
"""Device alarm control panel for BikeTrax devices."""
```

2022-10-17 19:54 UTC, basilfx commented
I finally found some time to take a look. I think it is a good addition, but I do have some doubts about the 'arm away' and 'arm home' situation. I do understand that its because of a bug in HASS: https://github.com/nielsfaber/alarmo/issues/384 (which is the opposite of this).

If we decide to remove 'arm home' (or 'arm away', although I would rather have an additional mode called 'arm'), then we end up with a broken UI. If we do include it, the status would be reset to 'arm away' after a restart.

From a usability perspective, I think it would be OK to leave it like this, and maybe fix it in the future. In that case, I could you add a code comment to highlight the whole issue? Maybe refer to this PR for more information? The known issues in the README also needs an update.

2022-10-17 19:55 UTC, basilfx commented
And if possible, can you try to rebase your changes on top of master? I try to keep merge commits out of feature branches, so the history of master stays 'clean'. If that doesn't work, just add the commits necessary and I'll do the rebasing afterwards.

2022-10-17 19:56 UTC, basilfx commented
I'll probably not right away, but somewhere this week, so I can 'gather' and 'fix' 0.3.0 issues if necessary. This will be 0.4.0.

2022-10-17 21:31 UTC, vlebourl commented
see #46.

2022-10-17 21:31 UTC, closed without merging